CREATE TABLE IF NOT EXISTS "Tasks"
(
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	"Content"	TEXT,
	"Deadline"	TEXT NOT NULL DEFAULT '9999-12-31',
	"FulfillmentDate"	TEXT,
	"Plan"	TEXT,
	"Fact"	TEXT
)