CREATE TABLE IF NOT EXISTS "Works"
(
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"TaskID"	INTEGER NOT NULL,
	"Content"	TEXT NOT NULL,
	"Date"	TEXT NOT NULL,
	"TimeSpent"	TEXT NOT NULL DEFAULT '00:00:00',
	FOREIGN KEY("TaskID") REFERENCES "Tasks"("ID")
)