CREATE DATABASE task_accounting_test;

CREATE TABLE public.tasks (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(512) NOT NULL,
	"content" text NULL,
	deadline date NULL,
	fulfillmentdate date NULL,
	plan interval NULL,
	fact interval NULL,
	CONSTRAINT tasks_name_key UNIQUE (name),
	CONSTRAINT tasks_pkey PRIMARY KEY (id)
);

CREATE TABLE public.works (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	taskid int8 NOT NULL,
	"content" text NOT NULL,
	"date" date NOT NULL,
	timespent interval NOT NULL,
	CONSTRAINT works_pkey PRIMARY KEY (id),
	CONSTRAINT works_taskid_fkey FOREIGN KEY (taskid) REFERENCES public.tasks(id)
);
